apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    name: docker-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: registry
    spec:
      containers:
        - resources:
          name: registry
          image: registry:2
          ports:
            - name: registry-port
              containerPort: 5000
          volumeMounts:
            - mountPath: /var/lib/registry
              name: images
            - mountPath: /certs
              name: certs
            - mountPath: /auth
              name: auth
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/cert.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/cert.key
      volumes:
        - name: images
          hostPath:
            path: /home/lucskylab/registry/images
        - name: certs
          hostPath:
            path: /home/lucskylab/registry/certs
        - name: auth
          hostPath:
            path: /home/lucskylab/registry/auth
      nodeSelector:
        node: master
