apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-ingress
spec:
#  tls:
#    - hosts:
#        - kubia.example.com
#      secretName: tls-secret
  rules:
    - host: kubia.example.com
      http:
        paths:
#          - path: /
#            backend:
#              serviceName: docker-registry
#              servicePort: 5000
          - path: /
            backend:
              serviceName: kubia-svc
              servicePort: 80
